name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Verification
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Creating .env
        run: |
          cat <<EOF > .env
          POSTGRESQL_USERNAME=postgres
          POSTGRESQL_PASSWORD=postgres
          POSTGRESQL_SERVER=localhost
          POSTGRESQL_PORT=5432
          POSTGRESQL_DATABASE=postgres
          DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
          DOMAIN=localhost
          ENVIRONMENT=local
          BACKEND_CORS_ORIGINS=https://localhost:8000
          JWT_SECRET_KEY=schedular
          EOF

      - name: Run docker compose
        run: docker compose up -d --build

      - name: Wait building
        run: sleep 10

      - name: Test endpoint
        run: curl --fail http://localhost:8000/health/ 

      - name: Closing containers
        if: always()
        run: docker compose down
